# Generated by Django 5.1.3 on 2024-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="pages",
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
