# Generated by Django 5.1.3 on 2024-11-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
