# Generated by Django 5.1.3 on 2024-11-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_book_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(editable=False, primary_key=True, serialize=False),
        ),
    ]
